-- 코드를 입력하세요


# 일단, 자동차 종류가 세단, 또는 SUV인 자동차를 뽑는다.
# 2022년 11월 1일부터 22년 11월 30일까지 대여가 가능해야 함
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
# 할인율 적용해야 함, 그러려면 자동차의 타입을 알아야 함.
# 
# 마지막 셀렉트 : ID, 종류, 대여금액(컬럼명 FEE)
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * ((100- B.DISCOUNT_RATE)/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE CAR_ID NOT in (
    SELECT A.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR A LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01'
    # WHERE (B.START_DATE NOT BETWEEN '2022-10-31' AND '2022-11-30'
    # AND B.END_DATE NOT BETWEEN '2022-1-01' AND '2022-11-30')
) 
AND A.CAR_TYPE in ('세단','SUV')
AND (A.CAR_TYPE = B.CAR_TYPE AND B.DURATION_TYPE='30일 이상')
GROUP BY A.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

# SELECT C.CAR_ID,
#        C.CAR_TYPE,
#        ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/100) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS C
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
# ON C.CAR_TYPE = P.CAR_TYPE 
# AND P.DURATION_TYPE = '30일 이상'
# WHERE C.CAR_TYPE IN ('세단', 'SUV')
# AND C.CAR_ID NOT IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
#     )
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;