-- 코드를 작성해주세요

select A.ID, B.FISH_NAME, A.LENGTH
from FISH_INFO A
INNER JOIN FISH_NAME_INFO B
on A.FISH_TYPE = B.FISH_TYPE
WHERE A.FISH_TYPE IN 
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
